'use client'
import { useState, type ChangeEvent, type FormEvent } from 'react'

type FormData = { firstName: string; lastName: string; organization: string; email: string; consent: boolean }
const initial: FormData = { firstName: '', lastName: '', organization: '', email: '', consent: false }

export default function HomePage() {
  const [submitted, setSubmitted] = useState(false)
  const [data, setData] = useState<FormData>(initial)
  const change = (event: ChangeEvent<HTMLInputElement>) => setData((current) => ({ ...current, [event.target.name]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }))
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <main className="min-h-screen bg-[#f5f7fa] md:flex">
    <aside className="bg-[#1c2e5a] p-6 text-white md:min-h-screen md:w-60"><strong className="font-['Space_Grotesk'] text-2xl">OAK</strong><p className="mt-12 text-[10px] tracking-[1.5px] text-[#aebbd0]">PARTNER PLATFORM</p><nav className="mt-5 grid gap-2"><button className="rounded-lg bg-[#24416f] p-3 text-left">□ Registration</button><button className="p-3 text-left text-[#aebbd0]">◎ Attendees</button><button className="p-3 text-left text-[#aebbd0]">≡ Programme</button></nav></aside>
    <section className="mx-auto w-full max-w-[1080px] p-4 sm:p-8"><header className="mb-7"><p className="text-[10px] font-bold tracking-[1.5px] text-[#8c99ab]">OAK ZIMBABWE</p><h1 className="font-['Space_Grotesk'] text-2xl font-semibold">Partner Gathering</h1></header><div className="rounded-xl bg-[#1c2e5a] p-7 text-white"><span className="rounded-full bg-[#24416f] px-3 py-1.5 text-[11px] text-[#dce6f7]">● Registration open</span><h2 className="mt-5 font-['Space_Grotesk'] text-3xl font-semibold">Partner Convening 2026</h2><p className="mt-3 text-sm text-[#aebbd0]">18–20 March 2026 · Harare, Zimbabwe</p></div><div className="mx-auto mt-6 max-w-[760px] rounded-[10px] border border-[#e4e8ef] bg-white p-6 sm:p-8"><p className="text-[10px] font-bold tracking-[1.5px] text-[#99a5b5]">YOUR DETAILS</p><h2 className="mb-6 mt-2 font-['Space_Grotesk'] text-2xl font-semibold">Register to attend</h2>{submitted ? <div className="py-8 text-center"><div className="mx-auto mb-4 grid size-14 place-items-center rounded-full bg-[#dce6f7] text-2xl">✓</div><h3 className="text-xl font-semibold">Registration received</h3><button onClick={() => setSubmitted(false)} className="mt-4 text-xs underline">Edit registration</button></div> : <form onSubmit={submit} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label>First name<input required name="firstName" value={data.firstName} onChange={change} placeholder="e.g. Tendai" /></label><label>Last name<input required name="lastName" value={data.lastName} onChange={change} placeholder="e.g. Moyo" /></label></div><label>Organisation<input required name="organization" value={data.organization} onChange={change} placeholder="Your organisation" /></label><label>Email address<input required type="email" name="email" value={data.email} onChange={change} placeholder="name@organisation.org" /></label><label className="flex grid-cols-none items-center gap-2 font-normal"><input required type="checkbox" name="consent" checked={data.consent} onChange={change} className="size-4" />I confirm that the details provided are accurate.</label><button className="rounded bg-[#1c2e5a] p-3 text-left font-semibold text-white" type="submit">Continue registration <span className="float-right">→</span></button></form>}</div><footer className="pt-6 text-xs text-[#9aa5b5]">Need help? events@oak.org.zw</footer></section>
  </main>
}