"use client";

import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import type { ReactNode } from "react";

export type Role = "Partner" | "OAK Staff" | "Presenter" | "Observer" | "Coordination Team";
const roleStyles: Record<Role, string> = { Partner: "bg-slate-100 text-slate-700", "OAK Staff": "bg-emerald-100 text-emerald-800", Presenter: "bg-sky-100 text-sky-800", Observer: "bg-indigo-100 text-indigo-800", "Coordination Team": "bg-amber-100 text-amber-800" };
export function Badge({ children, role }: { children: ReactNode; role?: Role }) { return <span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${role ? roleStyles[role] : "bg-slate-100 text-slate-600"}`}>{children}</span>; }
export function Header({ dark = false }: { dark?: boolean }) { return <header className={`${dark ? "bg-[#0d131f]" : "bg-[#182c53]"} text-white`}><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center"><Image src="/logo/logo.png" alt="OAK Foundation Partner Convening 2026" width={166} height={80} className="h-14 w-auto rounded bg-white object-contain" priority /></Link><div className="hidden text-right sm:block"><p className="text-sm font-semibold">Partner Convening 2026</p><p className="text-xs text-white/65">Cresta Lodge, Harare · 9–11 November 2026</p></div></div></header>; }
const nav = [["+", "Register", "/", "all"], ["⌗", "Check In", "/admin/check-in", "coord"], ["☷", "Programme", "/programme", "workspace"], ["▦", "Partners", "/directory", "workspace"], ["◉", "Attendance", "/admin/attendance", "coord"]];
export function BottomNav({ role = "Coordination Team" }: { role?: Role }) { const pathname = usePathname(); return <nav className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white/95 px-2 py-2 shadow-[0_-8px_30px_rgba(15,23,42,.08)] backdrop-blur"><div className="mx-auto flex max-w-2xl justify-between gap-1">{nav.filter((item) => item[3] === "all" || (item[3] === "workspace" && role !== "Partner") || role === "Coordination Team").map(([icon, label, href]) => <Link key={label} href={href} className={`flex min-w-14 flex-1 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[10px] font-bold ${pathname === href ? "bg-slate-900 text-white" : "text-slate-500 hover:bg-slate-100"}`}><span className="text-lg leading-none">{icon}</span>{label}</Link>)}</div></nav>; }
export function Frame({ children, role, dark = false }: { children: ReactNode; role?: Role; dark?: boolean }) { return <div className={`min-h-screen pb-24 ${dark ? "bg-[#0d131f]" : "bg-[#f8fafc]"}`}><Header dark={dark} />{children}{role && <BottomNav role={role} />}</div>; }
export function Title({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <div className="mb-7"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.2em] text-emerald-600">{eyebrow}</p><h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{description}</p>}</div>; }
export function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl bg-white/10 px-4 py-3"><strong className="block text-xl">{value}</strong><span className="text-[10px] uppercase tracking-wider text-white/60">{label}</span></div>; }
