# Generated by Django 6.1.1 on 2026-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('sub_partner_program_area', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('partner', 'Partner'), ('oak_staff', 'OAK Staff'), ('coordination', 'Coordination Team'), ('presenter', 'Presenter'), ('observer', 'Observer')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('accessibility_requirements', models.TextField(blank=True)),
                ('travel_requirements', models.TextField(blank=True)),
                ('accommodation_requirements', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registration_status', models.BooleanField(default=True)),
            ],
        ),
    ]
